version: "3.8"
services:
  postgres:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    container_name: ed2_postgis
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: florida_statewide_crash_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data

volumes:
  postgres_data:
